import type { VanityConfig } from '../../config'
import type { VanityAutoImportDeclarationFile } from './autoImportPlan'
import { existsSync } from 'node:fs'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { VanityError } from '../../diagnostics'
import { getAutoImportDeclarationPaths, planAutoImportDeclarations } from './autoImportPlan'

const generatedMarker = 'generated by vanity'
const externalAutoImportMarker = 'Generated by unplugin-auto-import'

/** Reconciliation result for one generated auto-import declaration plan. */
export interface VanityAutoImportWriteResult {
  readonly plan: Awaited<ReturnType<typeof planAutoImportDeclarations>>
  readonly written: readonly string[]
  readonly unchanged: readonly string[]
  readonly removed: readonly string[]
}

export interface AutoImportDeclarationWriteResult {
  readonly written: readonly string[]
  readonly unchanged: readonly string[]
}

export async function writeAutoImportDeclarations(
  options: VanityConfig,
  context: { root: string },
): Promise<VanityAutoImportWriteResult> {
  const plan = await planAutoImportDeclarations(options, context)
  const current = await writeAutoImportDeclarationFiles([...plan.declarations, ...plan.bridges])
  const removed: string[] = []
  const expected = new Set([...plan.declarations, ...plan.bridges].map(file => file.path))

  for (const role of ['style', 'app'] as const) {
    const paths = getAutoImportDeclarationPaths(plan.root, role)
    const stale = [paths.declaration, paths.bridge]

    for (const path of stale) {
      if (expected.has(path))
        continue
      if (await removeGeneratedFile(path))
        removed.push(path)
    }
  }

  await assertDeclarationsReachable(plan)

  return { plan, ...current, removed }
}

async function assertDeclarationsReachable(
  plan: Awaited<ReturnType<typeof planAutoImportDeclarations>>,
): Promise<void> {
  if (plan.declarations.length === 0)
    return

  const tsconfig = join(plan.root, 'tsconfig.json')
  if (!existsSync(tsconfig))
    return

  const ts = await import('typescript')
  const loaded = ts.readConfigFile(tsconfig, ts.sys.readFile)
  if (loaded.error)
    return
  const parsed = ts.parseJsonConfigFileContent(loaded.config, ts.sys, plan.root, undefined, tsconfig)
  const files = new Set(parsed.fileNames.map(file => file.replaceAll('\\', '/')))
  const registeredTypes = new Set(parsed.options.types ?? [])
  const missing = plan.declarations.filter((file) => {
    if (files.has(file.path.replaceAll('\\', '/')))
      return false

    const typeEntry = file.role === 'style'
      ? 'vanity-style-auto-imports'
      : 'vanity-app-auto-imports'
    const bridge = plan.bridges.find(candidate => candidate.role === file.role)
    return !registeredTypes.has(typeEntry) || bridge === undefined || !existsSync(bridge.path)
  })
  if (missing.length === 0)
    return

  const entries = missing.map(file =>
    file.role === 'style' ? 'vanity-style-auto-imports' : 'vanity-app-auto-imports')
  throw new VanityError({
    code: 'VANITY_AUTO_IMPORT_DECLARATIONS_NOT_INCLUDED',
    message: `${tsconfig} does not include Vanity's generated declarations`,
    path: ['compilerOptions', 'types'],
    fix: `add ${entries.map(entry => `'${entry}'`).join(' and ')} to compilerOptions.types, or include ${missing.map(file => `'${file.path}'`).join(' and ')}`,
  })
}

/** Reconcile a selected set of Vanity-owned declaration files. */
export async function writeAutoImportDeclarationFiles(
  files: readonly VanityAutoImportDeclarationFile[],
): Promise<AutoImportDeclarationWriteResult> {
  const written: string[] = []
  const unchanged: string[] = []

  for (const file of files) {
    const status = await reconcileGeneratedFile(file)
    if (status === 'written')
      written.push(file.path)
    else
      unchanged.push(file.path)
  }

  return { written, unchanged }
}

async function reconcileGeneratedFile(file: VanityAutoImportDeclarationFile): Promise<'written' | 'unchanged'> {
  const existing = await readOptional(file.path)
  if (existing === file.text)
    return 'unchanged'

  if (existing !== undefined && !isOwnedGeneratedFile(existing)) {
    throw new VanityError({
      code: 'VANITY_AUTO_IMPORT_INVALID',
      message: `refusing to overwrite a non-Vanity file at ${file.path}`,
      path: [file.path],
      fix: 'move the file aside or remove the manual declaration before preparing Vanity',
    })
  }

  await mkdir(dirname(file.path), { recursive: true })
  await writeFile(file.path, file.text)
  return 'written'
}

async function removeGeneratedFile(path: string): Promise<boolean> {
  const existing = await readOptional(path)
  if (existing === undefined)
    return false

  if (!isOwnedGeneratedFile(existing)) {
    throw new VanityError({
      code: 'VANITY_AUTO_IMPORT_INVALID',
      message: `refusing to remove a non-Vanity file at ${path}`,
      path: [path],
      fix: 'remove the file manually if it is no longer needed, or keep the corresponding auto-import module role enabled',
    })
  }

  await rm(path, { force: true })
  return true
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  }
  catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT')
      return undefined
    throw error
  }
}

function isOwnedGeneratedFile(source: string): boolean {
  return source.includes(generatedMarker) || source.includes(externalAutoImportMarker)
}
