import { dirname, isAbsolute, relative } from 'node:path'
import { VanityError } from '../../diagnostics'
import { normalizePath } from '../core/path'

const identifierPattern = /^[$a-z_][$\w]*$/i

/** Source module and named exports used to render an ambient declaration. */
export interface VanityAutoImportDeclarationSource {
  /** Module specifier written into the generated `typeof import(...)` type. */
  readonly from: string
  /** Named value exports exposed by the generated declaration. */
  readonly imports: readonly string[]
}

/** Generated declaration or type-discovery bridge owned by Vanity. */
export interface VanityAutoImportDeclarationFile {
  /** The module role whose declarations this file supplies. */
  readonly role: 'style' | 'app'
  readonly kind: 'declaration' | 'bridge'
  /** Whether a host should add the canonical declaration to its TS program. */
  readonly typeScriptReference: boolean
  readonly path: string
  readonly text: string
}

export function renderStyleAutoImportDeclarations(
  sources: readonly VanityAutoImportDeclarationSource[],
  options: { relativeTo?: string } = {},
): string {
  const entries = getEntriesFor(sources, 'style auto-import', options.relativeTo)
  const declarations = entries.map(entry =>
    `  /** Auto-imported from ${entry.from}. */\n  var ${entry.name}: typeof import(${JSON.stringify(entry.from)}).${entry.name}`,
  )

  return [
    '/* generated by vanity — do not edit */',
    '/* eslint-disable vars-on-top */',
    'declare global {',
    ...declarations,
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderAppAutoImportDeclarations(
  sources: readonly VanityAutoImportDeclarationSource[],
  options: { declarationFile?: string, vueTemplates?: boolean } = {},
): string {
  const entries = getEntriesFor(sources, 'app auto-import', options.declarationFile)
  const declarations = entries.map(entry => [
    `  var ${entry.name}: typeof import(${JSON.stringify(entry.from)}).${entry.name}`,
  ])

  const lines = [
    '/* generated by vanity — do not edit */',
    '/* eslint-disable vars-on-top */',
    'export {}',
    'declare global {',
    ...declarations.flat(),
    '}',
  ]

  if (options.vueTemplates && entries.length > 0) {
    lines.push(
      '',
      'import type { UnwrapRef } from \'vue\'',
      'declare module \'vue\' {',
      '  interface GlobalComponents {}',
      '  interface ComponentCustomProperties {',
      ...entries.map(entry =>
        `    readonly ${entry.name}: UnwrapRef<typeof import(${JSON.stringify(getModuleSpecifier(entry.from, options.declarationFile))})['${entry.name}']>`,
      ),
      '  }',
      '}',
    )
  }

  lines.push('')
  return `${lines.join('\n')}`
}

function getEntriesFor(
  sources: readonly VanityAutoImportDeclarationSource[],
  kind: string,
  relativeTo: string | undefined,
): Array<VanityAutoImportDeclarationSource & { name: string }> {
  const entries = sources.flatMap(source => source.imports.map(name => ({
    ...source,
    from: getModuleSpecifier(source.from, relativeTo),
    name,
  }))).sort((left, right) => left.name.localeCompare(right.name) || left.from.localeCompare(right.from))

  const seen = new Map<string, string>()
  for (const entry of entries) {
    assertIdentifier(entry.name, kind)
    const previous = seen.get(entry.name)
    if (previous !== undefined && previous !== entry.from) {
      throw new VanityError({
        code: 'VANITY_AUTO_IMPORT_INVALID',
        message: `${kind} '${entry.name}' is provided by both '${previous}' and '${entry.from}'`,
        path: ['autoImports', entry.name],
        fix: 'rename the export or narrow one source with include/exclude',
      })
    }
    seen.set(entry.name, entry.from)
  }

  return entries.filter((entry, index) => index === 0 || entries[index - 1]!.name !== entry.name)
}

export function createGeneratedAutoImportBridge(relativeDeclarationPath: string): string {
  return [
    '/* generated by vanity — do not edit */',
    `/// <reference path=${JSON.stringify(normalizePath(relativeDeclarationPath))} />`,
    '',
  ].join('\n')
}

export function getModuleSpecifier(from: string, relativeTo?: string): string {
  if (relativeTo === undefined || !isAbsolute(from) || !isAbsolute(relativeTo))
    return normalizePath(from)

  const path = normalizePath(relative(dirname(relativeTo), from))
  return path.startsWith('.') ? path : `./${path}`
}

function assertIdentifier(name: string, kind: string): void {
  if (!identifierPattern.test(name)) {
    throw new VanityError({
      code: 'VANITY_AUTO_IMPORT_INVALID',
      message: `'${name}' cannot be exposed as a ${kind} global`,
      path: ['autoImports', name],
      fix: 'expose a valid TypeScript identifier as an auto-import global',
    })
  }
}
