import { dirname, isAbsolute, relative } from 'node:path'
import { normalizePath } from '@vanilla-extract/integration'

const identifierPattern = /^[$a-z_][$\w]*$/i

export interface AutoImportDeclarationSource {
  readonly from: string
  readonly imports: readonly string[]
}

export interface AutoImportDeclarationFile {
  /** The module role whose declarations this file supplies. */
  readonly role: 'style' | 'app'
  readonly kind: 'declaration' | 'bridge'
  /** Whether a host should add the canonical declaration to its TS program. */
  readonly typeScriptReference: boolean
  readonly path: string
  readonly text: string
}

export function styleAutoImportDeclarations(
  sources: readonly AutoImportDeclarationSource[],
  options: { relativeTo?: string } = {},
): string {
  const entries = entriesFor(sources, 'style auto-import', options.relativeTo)
  const declarations = entries.map(entry =>
    `  /** Auto-imported from ${entry.from}. */\n  var ${entry.name}: typeof import(${JSON.stringify(entry.from)}).${entry.name}`,
  )

  return [
    '/* generated by vanity — do not edit */',
    '/* eslint-disable vars-on-top */',
    'declare global {',
    ...declarations,
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function appAutoImportDeclarations(
  sources: readonly AutoImportDeclarationSource[],
  options: { declarationFile?: string, vueTemplates?: boolean } = {},
): string {
  const entries = entriesFor(sources, 'app auto-import', options.declarationFile)
  const declarations = entries.map(entry => [
    `  var ${entry.name}: typeof import(${JSON.stringify(entry.from)}).${entry.name}`,
  ])

  const lines = [
    '/* generated by vanity — do not edit */',
    '/* eslint-disable vars-on-top */',
    'export {}',
    'declare global {',
    ...declarations.flat(),
    '}',
  ]

  if (options.vueTemplates && entries.length > 0) {
    lines.push(
      '',
      'import type { UnwrapRef } from \'vue\'',
      'declare module \'vue\' {',
      '  interface GlobalComponents {}',
      '  interface ComponentCustomProperties {',
      ...entries.map(entry =>
        `    readonly ${entry.name}: UnwrapRef<typeof import(${JSON.stringify(moduleSpecifierFor(entry.from, options.declarationFile))})['${entry.name}']>`,
      ),
      '  }',
      '}',
    )
  }

  lines.push('')
  return `${lines.join('\n')}`
}

function entriesFor(
  sources: readonly AutoImportDeclarationSource[],
  kind: string,
  relativeTo: string | undefined,
): Array<AutoImportDeclarationSource & { name: string }> {
  const entries = sources.flatMap(source => source.imports.map(name => ({
    ...source,
    from: moduleSpecifierFor(source.from, relativeTo),
    name,
  }))).sort((left, right) => left.name.localeCompare(right.name) || left.from.localeCompare(right.from))

  const seen = new Map<string, string>()
  for (const entry of entries) {
    assertIdentifier(entry.name, kind)
    const previous = seen.get(entry.name)
    if (previous !== undefined && previous !== entry.from) {
      throw new TypeError(
        `[vanity] ${kind} '${entry.name}' is provided by both '${previous}' and '${entry.from}'`,
      )
    }
    seen.set(entry.name, entry.from)
  }

  return entries.filter((entry, index) => index === 0 || entries[index - 1]!.name !== entry.name)
}

export function generatedAutoImportBridge(relativeDeclarationPath: string): string {
  return [
    '/* generated by vanity — do not edit */',
    `/// <reference path=${JSON.stringify(normalizePath(relativeDeclarationPath))} />`,
    '',
  ].join('\n')
}

export function moduleSpecifierFor(from: string, relativeTo?: string): string {
  if (relativeTo === undefined || !isAbsolute(from) || !isAbsolute(relativeTo))
    return normalizePath(from)

  const path = normalizePath(relative(dirname(relativeTo), from))
  return path.startsWith('.') ? path : `./${path}`
}

export function assertIdentifier(name: string, kind: string): void {
  if (!identifierPattern.test(name))
    throw new TypeError(`[vanity] '${name}' cannot be exposed as a ${kind} global`)
}
