import { dirname, isAbsolute, relative } from 'node:path'
import { normalizePath } from '@vanilla-extract/integration'

const identifierPattern = /^[$a-z_][$\w]*$/i

export interface AutoImportDeclarationSource {
  readonly from: string
  readonly imports: readonly string[]
}

export interface AutoImportDeclarationFile {
  readonly lane: 'style' | 'runtime'
  readonly kind: 'declaration' | 'bridge'
  /** Whether a host should add the canonical declaration to its TS program. */
  readonly typeScriptReference: boolean
  readonly path: string
  readonly text: string
}

export function styleAutoImportDeclarations(
  from: string,
  names: readonly string[],
  options: { relativeTo?: string } = {},
): string {
  const moduleSpecifier = moduleSpecifierFor(from, options.relativeTo)
  const declarations = names.map((name) => {
    assertIdentifier(name, 'style auto-import')
    return `  /** Auto-imported from ${moduleSpecifier}. */\n  const ${name}: typeof VanityStyleAutoImports.${name}`
  })

  return [
    '/* generated by vanity — do not edit */',
    `import type * as VanityStyleAutoImports from ${JSON.stringify(moduleSpecifier)}`,
    '',
    'declare global {',
    ...declarations,
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function runtimeAutoImportDeclarations(
  sources: readonly AutoImportDeclarationSource[],
  options: { declarationFile?: string, vueTemplates?: boolean } = {},
): string {
  const entries = sources.flatMap(source => source.imports.map(name => ({ ...source, name })))
    .sort((left, right) => left.name.localeCompare(right.name))

  const seen = new Map<string, string>()
  for (const entry of entries) {
    assertIdentifier(entry.name, 'runtime auto-import')
    const previous = seen.get(entry.name)
    if (previous !== undefined) {
      throw new TypeError(
        `[vanity] runtime auto-import '${entry.name}' is provided by both '${previous}' and '${entry.from}'`,
      )
    }
    seen.set(entry.name, entry.from)
  }

  const declarations = entries.map(entry => [
    `  const ${entry.name}: typeof import(${JSON.stringify(moduleSpecifierFor(entry.from, options.declarationFile))}).${entry.name}`,
  ])

  const lines = [
    '/* generated by vanity — do not edit */',
    'export {}',
    'declare global {',
    ...declarations.flat(),
    '}',
  ]

  if (options.vueTemplates && entries.length > 0) {
    lines.push(
      '',
      'import type { UnwrapRef } from \'vue\'',
      'declare module \'vue\' {',
      '  interface GlobalComponents {}',
      '  interface ComponentCustomProperties {',
      ...entries.map(entry =>
        `    readonly ${entry.name}: UnwrapRef<typeof import(${JSON.stringify(moduleSpecifierFor(entry.from, options.declarationFile))})['${entry.name}']>`,
      ),
      '  }',
      '}',
    )
  }

  lines.push('')
  return `${lines.join('\n')}`
}

export function generatedAutoImportBridge(relativeDeclarationPath: string): string {
  return [
    '/* generated by vanity — do not edit */',
    `/// <reference path=${JSON.stringify(normalizePath(relativeDeclarationPath))} />`,
    '',
  ].join('\n')
}

export function moduleSpecifierFor(from: string, relativeTo?: string): string {
  if (relativeTo === undefined || !isAbsolute(from) || !isAbsolute(relativeTo))
    return normalizePath(from)

  const path = normalizePath(relative(dirname(relativeTo), from))
  return path.startsWith('.') ? path : `./${path}`
}

export function assertIdentifier(name: string, kind: string): void {
  if (!identifierPattern.test(name))
    throw new TypeError(`[vanity] '${name}' cannot be exposed as a ${kind} global`)
}
