import type { VanityConfig } from '../config'
import type { AutoImportDeclarationFile } from './autoImportPlan'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { autoImportDeclarationPaths, planAutoImportDeclarations } from './autoImportPlan'

const generatedMarker = 'generated by vanity'
const legacyRuntimeMarker = 'Generated by unplugin-auto-import'

export interface VanityAutoImportWriteResult {
  readonly plan: Awaited<ReturnType<typeof planAutoImportDeclarations>>
  readonly written: readonly string[]
  readonly unchanged: readonly string[]
  readonly removed: readonly string[]
}

export interface AutoImportDeclarationWriteResult {
  readonly written: readonly string[]
  readonly unchanged: readonly string[]
}

export async function writeAutoImportDeclarations(
  options: VanityConfig,
  context: { root: string },
): Promise<VanityAutoImportWriteResult> {
  const plan = await planAutoImportDeclarations(options, context)
  const current = await writeAutoImportDeclarationFiles([...plan.declarations, ...plan.bridges])
  const removed: string[] = []
  const expected = new Set([...plan.declarations, ...plan.bridges].map(file => file.path))

  for (const lane of ['style', 'runtime'] as const) {
    const paths = autoImportDeclarationPaths(plan.root, lane)
    const stale = [
      paths.declaration,
      paths.bridge,
      ...(lane === 'style' ? [join(plan.root, 'node_modules', '.vanity', 'style-auto-imports.d.ts')] : []),
    ]

    for (const path of stale) {
      if (expected.has(path))
        continue
      if (await removeGeneratedFile(path))
        removed.push(path)
    }
  }

  return { plan, ...current, removed }
}

/** Reconcile a selected set of Vanity-owned declaration files. */
export async function writeAutoImportDeclarationFiles(
  files: readonly AutoImportDeclarationFile[],
): Promise<AutoImportDeclarationWriteResult> {
  const written: string[] = []
  const unchanged: string[] = []

  for (const file of files) {
    const status = await reconcileGeneratedFile(file)
    if (status === 'written')
      written.push(file.path)
    else
      unchanged.push(file.path)
  }

  return { written, unchanged }
}

async function reconcileGeneratedFile(file: AutoImportDeclarationFile): Promise<'written' | 'unchanged'> {
  const existing = await readOptional(file.path)
  if (existing === file.text)
    return 'unchanged'

  if (existing !== undefined && !isOwnedGeneratedFile(existing)) {
    throw new Error(
      `[vanity] refusing to overwrite a non-Vanity file at ${file.path}\n`
      + '  fix: move the file aside or remove the manual declaration before preparing Vanity',
    )
  }

  await mkdir(dirname(file.path), { recursive: true })
  await writeFile(file.path, file.text)
  return 'written'
}

async function removeGeneratedFile(path: string): Promise<boolean> {
  const existing = await readOptional(path)
  if (existing === undefined)
    return false

  if (!isOwnedGeneratedFile(existing)) {
    throw new Error(
      `[vanity] refusing to remove a non-Vanity file at ${path}\n`
      + '  fix: remove the file manually if it is obsolete, or keep the corresponding auto-import lane enabled',
    )
  }

  await rm(path, { force: true })
  return true
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  }
  catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT')
      return undefined
    throw error
  }
}

function isOwnedGeneratedFile(source: string): boolean {
  return source.includes(generatedMarker) || source.includes(legacyRuntimeMarker)
}
