/**
 * Product-side depth guard for the lean accumulation law proven by
 * spikes/type-accumulation. Eighty independent links exceeded the naive
 * Simplify-at-every-step failure point by 2× when that spike was accepted.
 */
import { createSystem } from '@mszr/vanity'
import { describe, expectTypeOf, it } from 'vitest'

describe('open-system accumulation depth', () => {
  it('keeps eighty links and independent locked forks below TS2589', () => {
    const base = createSystem()
      .addConsts({ c00: 0 })
      .addConsts({ c01: 1 })
      .addConsts({ c02: 2 })
      .addConsts({ c03: 3 })
      .addConsts({ c04: 4 })
      .addConsts({ c05: 5 })
      .addConsts({ c06: 6 })
      .addConsts({ c07: 7 })
      .addConsts({ c08: 8 })
      .addConsts({ c09: 9 })
      .addConsts({ c10: 10 })
      .addConsts({ c11: 11 })
      .addConsts({ c12: 12 })
      .addConsts({ c13: 13 })
      .addConsts({ c14: 14 })
      .addConsts({ c15: 15 })
      .addConsts({ c16: 16 })
      .addConsts({ c17: 17 })
      .addConsts({ c18: 18 })
      .addConsts({ c19: 19 })
      .addConsts({ c20: 20 })
      .addConsts({ c21: 21 })
      .addConsts({ c22: 22 })
      .addConsts({ c23: 23 })
      .addConsts({ c24: 24 })
      .addConsts({ c25: 25 })
      .addConsts({ c26: 26 })
      .addConsts({ c27: 27 })
      .addConsts({ c28: 28 })
      .addConsts({ c29: 29 })
      .addConsts({ c30: 30 })
      .addConsts({ c31: 31 })
      .addConsts({ c32: 32 })
      .addConsts({ c33: 33 })
      .addConsts({ c34: 34 })
      .addConsts({ c35: 35 })
      .addConsts({ c36: 36 })
      .addConsts({ c37: 37 })
      .addConsts({ c38: 38 })
      .addConsts({ c39: 39 })
      .addConsts({ c40: 40 })
      .addConsts({ c41: 41 })
      .addConsts({ c42: 42 })
      .addConsts({ c43: 43 })
      .addConsts({ c44: 44 })
      .addConsts({ c45: 45 })
      .addConsts({ c46: 46 })
      .addConsts({ c47: 47 })
      .addConsts({ c48: 48 })
      .addConsts({ c49: 49 })
      .addConsts({ c50: 50 })
      .addConsts({ c51: 51 })
      .addConsts({ c52: 52 })
      .addConsts({ c53: 53 })
      .addConsts({ c54: 54 })
      .addConsts({ c55: 55 })
      .addConsts({ c56: 56 })
      .addConsts({ c57: 57 })
      .addConsts({ c58: 58 })
      .addConsts({ c59: 59 })
      .addConsts({ c60: 60 })
      .addConsts({ c61: 61 })
      .addConsts({ c62: 62 })
      .addConsts({ c63: 63 })
      .addConsts({ c64: 64 })
      .addConsts({ c65: 65 })
      .addConsts({ c66: 66 })
      .addConsts({ c67: 67 })
      .addConsts({ c68: 68 })
      .addConsts({ c69: 69 })
      .addConsts({ c70: 70 })
      .addConsts({ c71: 71 })
      .addConsts({ c72: 72 })
      .addConsts({ c73: 73 })
      .addConsts({ c74: 74 })
      .addConsts({ c75: 75 })
      .addConsts({ c76: 76 })
      .addConsts({ c77: 77 })
      .addConsts({ c78: 78 })
      .addConsts({ c79: 79 })

    const first = base.addTokens({ first: { value: 'red' } }).consolidate({ prefix: 'first' })
    const second = base.addTokens({ second: { value: 'blue' } }).consolidate({ prefix: 'second' })

    expectTypeOf(first.consts.c00).toEqualTypeOf<0>()
    expectTypeOf(first.consts.c79).toEqualTypeOf<79>()
    expectTypeOf(first.t.first.value.$name).toEqualTypeOf<'--first-first-value'>()
    expectTypeOf(second.t.second.value.$name).toEqualTypeOf<'--second-second-value'>()
  })
})
