/**
 * Deterministic generator for realistic whole-system chains.
 *
 * A profile produces a chain with the call mix a real system build has:
 * variant sets up front, early contributions, many wide groups (fields are a
 * fixed mix of plain / branched-over-variants / one-level nested), periodic
 * `derive` reads of earlier groups, late contributions whose requirements
 * reach back across the chain, and batched helpers — then `consolidate()`
 * plus probes that force the first and last groups to have survived.
 *
 * Used by measure.mjs (temp files at every profile) and by `pnpm generate`
 * (writes generated/m.ts, the committed module the selenita tests query).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const PROFILES = {
  S: { groups: 10, fields: 8 },
  M: { groups: 30, fields: 10 },
  L: { groups: 60, fields: 12 },
  XL: { groups: 100, fields: 15 },
  XXL: { groups: 150, fields: 20 },
}

function fieldSrc(i) {
  if (i % 10 === 9)
    return `sub${i}: { s0: 'x', s1: { light: 'p', dark: 'q' }, s2: 4 }`
  if (i % 4 === 2)
    return `f${i}: { light: 'l${i}', dark: 'd${i}' }`
  if (i % 7 === 3)
    return `f${i}: { compact: ${i}, cozy: ${i + 1}, comfortable: ${i + 2} }`
  return i % 2 === 0 ? `f${i}: 'v${i}'` : `f${i}: ${i}`
}

function groupSrc(k, fields) {
  const body = Array.from({ length: fields }, (_, i) => fieldSrc(i)).join(', ')
  return `  .group('g${k}', { ${body} })`
}

/** 8 contributions: a chain where each requires what an earlier one provides. */
function contributionsSrc() {
  const lines = []
  for (let i = 0; i < 8; i++) {
    const requires = i === 0
      ? '{}'
      : i < 4
        ? `{ ctl${i - 1}: ['a${i - 1}'] }`
        : `{ ctl${i - 1}: ['a${i - 1}'], g0: ['f0'] }` // late ones also require USER groups
    lines.push(`const p${i} = contribution({ id: 'p${i}', requires: ${requires}, provides: { ctl${i}: { a${i}: ${i}, b${i}: 'x', c${i}: { light: 1, dark: 2 } } } })`)
  }
  return lines.join('\n')
}

function helpersSrc(batch) {
  const body = Array.from({ length: 10 }, (_, i) => `h${batch}_${i}: (n: number) => n + ${i}`).join(', ')
  return `  .helpers({ ${body} })`
}

/**
 * @param {{ groups: number, fields: number }} profile
 * @param {{ importPath: string, probes?: boolean }} opts
 */
export function genSystem({ groups, fields }, { importPath, probes = true }) {
  const lines = []
  lines.push(`import { contribution, createSystem } from '${importPath}'`, '')
  lines.push(contributionsSrc(), '')
  lines.push('export const sys = createSystem()')
  lines.push(`  .variants('scheme', ['light', 'dark'])`)
  lines.push(`  .variants('density', ['compact', 'cozy', 'comfortable'])`)
  lines.push(`  .variants('motion', ['full', 'reduced'])`)
  lines.push('  .use(p0)', '  .use(p1)', '  .use(p2)', '  .use(p3)')
  for (let k = 0; k < groups; k++) {
    lines.push(groupSrc(k, fields))
    // every 10th group, a derive that READS earlier accumulate (forces Simplify)
    if (k > 0 && k % 10 === 0)
      lines.push(`  .derive(t => ({ d${k}: { a: t.g${k - 1}.f0, b: t.g${Math.floor(k / 2)}.f1 } }))`)
  }
  lines.push('  .use(p4)', '  .use(p5)', '  .use(p6)', '  .use(p7)')
  lines.push(helpersSrc(0))
  lines.push(helpersSrc(1))
  lines.push('')
  lines.push('export const locked = sys.consolidate()')
  if (probes) {
    lines.push('')
    lines.push('// probes: accumulation must have held from the first group to the last')
    lines.push(`const first: string = locked.t.g0.f0`)
    lines.push(`const lastBranch: string = locked.t.g${groups - 1}.f2.dark`)
    lines.push(`const helper: number = locked.helpers.h1_9(1)`)
    lines.push(`const plugin: number = locked.t.ctl7.a7`)
    lines.push(`const groupKey: keyof typeof locked.t = 'g${groups - 1}'`)
    lines.push('void [first, lastBranch, helper, plugin, groupKey]')
  }
  lines.push('')
  return lines.join('\n')
}

// CLI: write the committed M-scale module the selenita tests import.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const here = fileURLToPath(new URL('.', import.meta.url))
  const out = join(here, '..', 'generated')
  mkdirSync(out, { recursive: true })
  writeFileSync(
    join(out, 'm.ts'),
    `/* GENERATED by scale/generate.mjs — do not edit. Regenerate: pnpm generate */\n${genSystem(PROFILES.M, { importPath: '../src/system' })}`,
  )
  console.log('wrote generated/m.ts (profile M)')
}
