/**
 * Deterministic generator for the library entry and the consumer probe.
 *
 * The chain mix mirrors spikes/system-scale (wide groups with plain / branched /
 * nested fields, contributions, derives, helpers) so results stay comparable.
 * Two exports from one entry:
 *   `ds`         — the NAIVE export: the raw consolidated chain type
 *   `dsPortable` — the boundary-simplified export via `portable()`
 *
 * Used by `pnpm generate` (writes the committed M-profile lib/src/index.ts and
 * app/src/consume.ts) and by emit/measure.mjs (per-profile work dirs).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const PROFILES = {
  M: { groups: 30, fields: 10 },
  L: { groups: 60, fields: 12 },
  XL: { groups: 100, fields: 15 },
}

function fieldSrc(i) {
  if (i % 10 === 9)
    return `sub${i}: { s0: 'x', s1: { light: 'p', dark: 'q' }, s2: 4 }`
  if (i % 4 === 2)
    return `f${i}: { light: 'l${i}', dark: 'd${i}' }`
  if (i % 7 === 3)
    return `f${i}: { compact: ${i}, cozy: ${i + 1}, comfortable: ${i + 2} }`
  return i % 2 === 0 ? `f${i}: 'v${i}'` : `f${i}: ${i}`
}

function contributionsSrc() {
  const lines = []
  for (let i = 0; i < 8; i++) {
    const requires = i === 0
      ? '{}'
      : i < 4
        ? `{ ctl${i - 1}: ['a${i - 1}'] }`
        : `{ ctl${i - 1}: ['a${i - 1}'], g0: ['f0'] }`
    lines.push(`const p${i} = contribution({ id: 'p${i}', requires: ${requires}, provides: { ctl${i}: { a${i}: ${i}, b${i}: 'x', c${i}: { light: 1, dark: 2 } } } })`)
  }
  return lines.join('\n')
}

/** The library entry: build the chain, export naive + portable surfaces. */
export function genLibEntry({ groups, fields }) {
  const lines = []
  lines.push(`import { contribution, createSystem, portable } from './system'`, '')
  lines.push(contributionsSrc(), '')
  lines.push('const open = createSystem()')
  lines.push(`  .variants('scheme', ['light', 'dark'])`)
  lines.push(`  .variants('density', ['compact', 'cozy', 'comfortable'])`)
  lines.push(`  .variants('motion', ['full', 'reduced'])`)
  lines.push('  .use(p0)', '  .use(p1)', '  .use(p2)', '  .use(p3)')
  for (let k = 0; k < groups; k++) {
    const body = Array.from({ length: fields }, (_, i) => fieldSrc(i)).join(', ')
    lines.push(`  .group('g${k}', { ${body} })`)
    if (k > 0 && k % 10 === 0)
      lines.push(`  .derive(t => ({ d${k}: { a: t.g${k - 1}.f0, b: t.g${Math.floor(k / 2)}.f1 } }))`)
  }
  lines.push('  .use(p4)', '  .use(p5)', '  .use(p6)', '  .use(p7)')
  for (const batch of [0, 1]) {
    const body = Array.from({ length: 10 }, (_, i) => `h${batch}_${i}: (n: number) => n + ${i}`).join(', ')
    lines.push(`  .helpers({ ${body} })`)
  }
  lines.push('')
  lines.push('/** NAIVE export: the raw consolidated chain type, serialized as-is. */')
  lines.push('export const ds = open.consolidate()')
  lines.push('')
  lines.push('/** PORTABLE export: boundary-simplified before crossing the package edge. */')
  lines.push('export const dsPortable = portable(ds)')
  lines.push('')
  return lines.join('\n')
}

/** The consumer probe: reads that force the emitted d.ts to carry the whole shape. */
export function genAppProbe({ groups }, importPath) {
  const last = groups - 1
  return [
    '// eslint-disable-next-line antfu/no-import-dist -- consuming the emitted d.ts (dist) IS this spike',
    `import { ds, dsPortable } from '${importPath}'`,
    '',
    '// reads across the full surface, from the emitted d.ts ALONE:',
    `const first: string = ds.t.g0.f0`,
    `const lastBranch: string = ds.t.g${last}.f2.dark`,
    `const helper: number = ds.helpers.h1_9(1)`,
    `const plugin: number = ds.t.ctl7.a7`,
    `const viaPortable: string = dsPortable.t.g${last}.f2.light`,
    `const readback: string = dsPortable.read('g0').f0`,
    'void [first, lastBranch, helper, plugin, viaPortable, readback]',
    '',
  ].join('\n')
}

// CLI: write the committed M-profile entry + probe.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const here = fileURLToPath(new URL('.', import.meta.url))
  const root = join(here, '..')
  mkdirSync(join(root, 'app', 'src'), { recursive: true })
  const banner = '/* GENERATED by emit/generate.mjs — do not edit. Regenerate: pnpm generate */\n'
  writeFileSync(join(root, 'lib', 'src', 'index.ts'), banner + genLibEntry(PROFILES.M))
  writeFileSync(join(root, 'app', 'src', 'consume.ts'), banner + genAppProbe(PROFILES.M, '../../lib/dist/index'))
  console.log('wrote lib/src/index.ts + app/src/consume.ts (profile M)')
}
