/**
 * Generates the parts a real build would produce — the design package's `dist`,
 * the host's `.vanity` declarations, and the `node_modules` links that make the
 * fixtures resolve as published packages — then runs every case in the matrix
 * and asserts clean-vs-errors against expectation.
 *
 * The only variable across the matrix is the keyword the generated ambient
 * declarations use: `const`, as vanity emits today, or `var`.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const at = path => resolve(root, path)

/** Byte-shaped like sdk/src/internal/autoImportDeclarations.ts, keyword aside. */
function ambientDeclaration(keyword) {
  return [
    '/* generated by vanity — do not edit */',
    'import type * as VanityStyleAutoImports from "@spike/design/authoring"',
    '',
    'declare global {',
    '  /** Auto-imported from @spike/design/authoring. */',
    `  ${keyword} cls: typeof VanityStyleAutoImports.cls`,
    '  /** Auto-imported from @spike/design/authoring. */',
    `  ${keyword} t: typeof VanityStyleAutoImports.t`,
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

function write(path, text) {
  mkdirSync(dirname(at(path)), { recursive: true })
  writeFileSync(at(path), text)
}

/** The design package as published: built JS + types, not source. */
function buildDesignPackage(keyword) {
  const source = readFileSync(at('packages/design/src/authoring.ts'), 'utf8')
  write('packages/design/dist/authoring.d.ts', [
    'export declare const cls: (rules: Record<string, unknown>) => string',
    'export declare const t: { readonly color: { readonly brand: string } }',
    '',
  ].join('\n'))
  write('packages/design/dist/authoring.js', source
    .replace(/^\/\*\*[\s\S]*?\*\/\n/, '')
    .replace(/: Record<string, unknown>\): string/, ')')
    .replace(/ as const/, ''))
  write('packages/design/dist/vanity-style-auto-imports.d.ts', ambientDeclaration(keyword))
  write('packages/design/dist/vanity-style-auto-imports.js', 'export {}\n')
}

function generate(keyword) {
  buildDesignPackage(keyword)
  write('host-generating/.vanity/types/vanity-style-auto-imports.d.ts', ambientDeclaration(keyword))

  mkdirSync(at('node_modules/@spike'), { recursive: true })
  for (const name of ['design', 'author-unlocked', 'author-bare', 'author-mixed']) {
    const link = at(`node_modules/@spike/${name}`)
    if (!existsSync(link))
      symlinkSync(resolve(root, 'packages', name), link, 'dir')
  }
}

function check(project) {
  try {
    execFileSync('npx', ['tsc', '-p', at(project)], { cwd: root, stdio: 'pipe' })
    return { ok: true, out: '' }
  }
  catch (error) {
    return { ok: false, out: String(error.stdout ?? '') }
  }
}

const cases = [
  ['const', 'consumer/tsconfig.unlocked.json', true, 'T1  intermediate consumer compiles source carrying the unlock import'],
  ['const', 'consumer/tsconfig.bare.json', false, 'T2  control: same source without it (reproduces the reported TS2304)'],
  ['const', 'host-generating/tsconfig.json', false, 'T3  host generating its own globals + consuming an unlocked package'],
  ['const', 'host-deferring/tsconfig.json', true, 'T4  host deferring to the package-provided declaration'],
  ['var', 'host-generating/tsconfig.json', true, 'T5  T3 again, with both declarations emitted as `var`'],
  ['var', 'conflict/tsconfig.divergent.json', false, 'T6  two `var` declarations, same name, divergent types'],
  ['var', 'conflict/tsconfig.identical.json', true, 'T7  two `var` declarations, same name, identical type'],
  ['const', 'consumer/tsconfig.mixed.json', true, 'T9  consumer of a package mixing explicit-import and unlock files'],
]

let failed = 0
for (const [keyword, project, expected, label] of cases) {
  generate(keyword)
  const { ok, out } = check(project)
  const pass = ok === expected
  if (!pass)
    failed++
  console.log(`${pass ? 'ok  ' : 'FAIL'}  ${label}`)
  console.log(`        declaration=${keyword}  typecheck=${ok ? 'clean' : 'errors'}  expected=${expected ? 'clean' : 'errors'}`)
  if (!ok && out.trim())
    console.log(out.trim().split('\n').map(line => `        ${line}`).join('\n'))
}

// T8 is the only case that emits, so it asserts on output rather than exit code.
generate('const')
rmSync(at('emit-check/dist'), { recursive: true, force: true })
const emit = check('emit-check/tsconfig.json')
const js = existsSync(at('emit-check/dist/Button.css.js')) ? readFileSync(at('emit-check/dist/Button.css.js'), 'utf8') : ''
const dts = existsSync(at('emit-check/dist/Button.css.d.ts')) ? readFileSync(at('emit-check/dist/Button.css.d.ts'), 'utf8') : ''
const elided = emit.ok && js.length > 0 && !js.includes('vanity-style-auto-imports') && !dts.includes('vanity-style-auto-imports')
if (!elided)
  failed++
console.log(`${elided ? 'ok  ' : 'FAIL'}  T8  unlock import under verbatimModuleSyntax, with real emit`)
console.log(`        typecheck=${emit.ok ? 'clean' : 'errors'}  emitted js=${JSON.stringify(js.trim())}`)
if (!emit.ok && emit.out.trim())
  console.log(emit.out.trim().split('\n').map(line => `        ${line}`).join('\n'))

console.log(failed === 0 ? '\nall cases matched expectation' : `\n${failed} case(s) diverged`)
process.exit(failed === 0 ? 0 : 1)
