import type { VanityAutoImportPlan } from './compiler/auto-imports/autoImportPlan'
import type { VanityAutoImportWriteResult } from './compiler/auto-imports/autoImportWriter'
import type { VanityConfig } from './config'
import { access } from 'node:fs/promises'
import { cwd } from 'node:process'
import { createJiti } from 'jiti'
import { planAutoImportDeclarations as plan } from './compiler/auto-imports/autoImportPlan'
import { writeAutoImportDeclarations as write } from './compiler/auto-imports/autoImportWriter'
import { resolveConfiguredModuleSource } from './compiler/projection/exportNames'

export type { AutoImportDeclarationSource } from './compiler/auto-imports/autoImportDeclarations'
export type {
  AutoImportDeclarationFile,
  AutoImportDeclarationPaths,
  VanityAppAutoImportPlan,
  VanityAutoImportPlan,
  VanityStyleAutoImportPlan,
} from './compiler/auto-imports/autoImportPlan'
export type { VanityAutoImportWriteResult } from './compiler/auto-imports/autoImportWriter'

/** Project root used to resolve source paths and generated declaration files. */
export interface VanityPrepareContext {
  root?: string
}

/**
 * Read-only, static declaration planning for a host's configured module-role routing.
 * The returned canonical files carry `typeScriptReference: true`, so a host
 * with its own preparation hook can register their text without granting
 * Vanity ownership of that hook or writing to its filesystem.
 */
export function planAutoImportDeclarations(
  options: VanityConfig,
  context: VanityPrepareContext = {},
): Promise<VanityAutoImportPlan> {
  return plan(options, { root: context.root ?? cwd() })
}

/**
 * Reconcile canonical declaration files and their TypeScript discovery
 * bridges. Only files generated by Vanity are overwritten or removed.
 */
export function writeAutoImportDeclarations(
  options: VanityConfig,
  context: VanityPrepareContext = {},
): Promise<VanityAutoImportWriteResult> {
  return write(options, { root: context.root ?? cwd() })
}

/**
 * Load a TypeScript Vanity configuration module. The CLI uses this helper so
 * consumers can author config with the same syntax as their host config.
 */
export async function loadVanityConfig(
  path: string,
  context: VanityPrepareContext = {},
): Promise<VanityConfig> {
  const root = context.root ?? cwd()
  const configPath = resolveConfiguredModuleSource(path, root, 'the --config option').file
  try {
    await access(configPath)
  }
  catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      throw new Error(
        `[vanity] no Vanity config found at ${configPath}\n`
        + '  fix: create vanity.config.ts, pass --config <path>, or use the programmatic preparation API',
      )
    }
    throw error
  }

  const loaded = await createJiti(import.meta.url).import<unknown>(configPath, { default: true })
  if (!loaded || typeof loaded !== 'object' || Array.isArray(loaded)) {
    throw new TypeError(
      `[vanity] config module '${configPath}' must export a Vanity configuration object`,
    )
  }
  return loaded as VanityConfig
}
