/* GENERATED by emit/generate.mjs — do not edit. Regenerate: pnpm generate */
// eslint-disable-next-line antfu/no-import-dist -- consuming the emitted d.ts (dist) IS this spike
import { ds, dsPortable } from '../../lib/dist/index'

// reads across the full surface, from the emitted d.ts ALONE:
const first: string = ds.t.g0.f0
const lastBranch: string = ds.t.g29.f2.dark
const helper: number = ds.helpers.h1_9(1)
const plugin: number = ds.t.ctl7.a7
const viaPortable: string = dsPortable.t.g29.f2.light
const readback: string = dsPortable.read('g0').f0
void [first, lastBranch, helper, plugin, viaPortable, readback]
